### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by zhaojc001** [huschen/kaggle_speech_recognition#3]
when I am training，it appears the following error，please help me:
root@ubuntu:/usr/local/zjc/SpeechRecognition/kaggle_speech_recognition# CUDA_VISIBLE_DEVICES=2,3 python3 train.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-04-01 14:53:15.798882: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-01 14:53:19.001114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8095
pciBusID: 0000:81:00.0
totalMemory: 7.92GiB freeMemory: 7.80GiB
2019-04-01 14:53:19.171378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8095
pciBusID: 0000:82:00.0
totalMemory: 7.92GiB freeMemory: 7.80GiB
2019-04-01 14:53:19.172627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0, 1
2019-04-01 14:53:19.940401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-01 14:53:19.940450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 1 
2019-04-01 14:53:19.940457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N Y 
2019-04-01 14:53:19.940462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 1:   Y N 
2019-04-01 14:53:19.940923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:0 with 7530 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:81:00.0, compute capability: 6.1)
2019-04-01 14:53:20.046612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:1 with 7530 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080, pci bus id: 0000:82:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 24, in main
    FLAGS.result_dir)
  File "/usr/local/zjc/SpeechRecognition/kaggle_speech_recognition/util_train.py", line 51, in train_init
    tf.logging._logger.addHandler(file_handler)
AttributeError: module 'tensorflow.logging' has no attribute '_logger'

**Comment by huschen** [comment]
You must be using a different version of Tensorflow. What version is it?
This line of code is to set up the file logging. It is likely the interface of tf.logging has changed. It should be easy to fix by replacing this line with the new logging API.
Let me know if you need more help :-)
